package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"sort"
	"strconv"
	"strings"
)

// Package references are emitted as tokens during rendering and replaced with
// import aliases afterwards, so alias assignment can be deterministic (sorted
// by import path) rather than dependent on the order types happen to be written.
const (
	tokenStart = "\x00pkg:"
	tokenEnd   = "\x00"

	// slogPath is the package the generated container logs through.
	slogPath = "log/slog"
)

type renderer struct {
	g *graph
	// pkgNames maps each referenced import path to its package name, which is
	// not always the last path segment (gocron/v2 is package gocron).
	pkgNames map[string]string
}

func render(g *graph) ([]byte, error) {
	r := &renderer{g: g, pkgNames: map[string]string{}}

	var body bytes.Buffer
	r.renderProxies(&body)
	r.renderContainer(&body)
	r.renderAccessors(&body)
	r.renderRoles(&body)
	r.renderGroups(&body)

	aliases := r.assignAliases()

	var out bytes.Buffer
	out.WriteString("// Code generated by digen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "package %s\n\n", g.pkgName)
	r.writeImports(&out, aliases)
	out.Write(body.Bytes())

	source := replaceTokens(out.String(), aliases)

	formatted, err := format.Source([]byte(source))
	if err != nil {
		return nil, fmt.Errorf("generated code is not valid Go: %w\n%s", err, numberLines(source))
	}
	return formatted, nil
}

// typeString renders a type with package references as tokens.
func (r *renderer) typeString(t types.Type) string {
	return types.TypeString(t, func(p *types.Package) string {
		if p == nil {
			return ""
		}
		r.pkgNames[p.Path()] = p.Name()
		return tokenStart + p.Path() + tokenEnd
	})
}

// funcRef renders a reference to a provider function, qualified if it is not in
// the package being generated into.
func (r *renderer) funcRef(p *provider) string {
	pkg := p.fn.Pkg()
	if pkg == nil || pkg.Path() == r.g.targetPath {
		return p.fn.Name()
	}
	r.pkgNames[pkg.Path()] = pkg.Name()
	return tokenStart + pkg.Path() + tokenEnd + "." + p.fn.Name()
}

func (r *renderer) assignAliases() map[string]string {
	paths := make([]string, 0, len(r.pkgNames))
	for p := range r.pkgNames {
		if p != r.g.targetPath {
			paths = append(paths, p)
		}
	}
	// Shallower paths claim the plain package name first, so internal/driver
	// keeps "driver" and internal/core/driver becomes "coredriver" — the same
	// convention the hand-written code in this repo uses.
	sort.Slice(paths, func(i, j int) bool {
		di, dj := strings.Count(paths[i], "/"), strings.Count(paths[j], "/")
		if di != dj {
			return di < dj
		}
		return paths[i] < paths[j]
	})

	aliases := make(map[string]string, len(paths))
	taken := map[string]bool{"main": true}

	for _, path := range paths {
		base := sanitizeIdent(lastSegment(path))
		if name := r.pkgNames[path]; name != "" {
			base = name
		}

		alias := base
		if taken[alias] {
			// Fold in the parent directory: internal/core/api becomes coreapi,
			// matching the convention already used by hand in this repo.
			if parent := parentSegment(path); parent != "" {
				alias = sanitizeIdent(parent) + base
			}
		}
		for i := 2; taken[alias]; i++ {
			alias = base + strconv.Itoa(i)
		}
		taken[alias] = true
		aliases[path] = alias
	}
	return aliases
}

func (r *renderer) writeImports(out *bytes.Buffer, aliases map[string]string) {
	if len(aliases) == 0 {
		return
	}
	paths := make([]string, 0, len(aliases))
	for p := range aliases {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	out.WriteString("import (\n")
	for _, p := range paths {
		fmt.Fprintf(out, "\t%s %q\n", aliases[p], p)
	}
	out.WriteString(")\n\n")
}

// renderProxies emits one lazy proxy per proxied provider: a value implementing
// the interface that builds the real one on first method call.
func (r *renderer) renderProxies(out *bytes.Buffer) {
	for _, nd := range r.g.nodes {
		if !nd.proxied {
			continue
		}

		typeName := r.proxyTypeName(nd.p)
		provided := r.typeString(nd.p.provides)

		fmt.Fprintf(out, "// %s defers construction of %s until first use.\n", typeName, typeLabel(nd.p.provides))
		fmt.Fprintf(out, "type %s struct {\n", typeName)
		fmt.Fprintf(out, "\tonce  %s.Once\n", r.pkgToken("sync"))
		fmt.Fprintf(out, "\tbuild func() %s\n", provided)
		fmt.Fprintf(out, "\tval   %s\n", provided)
		for i, t := range nd.p.alsoAs {
			fmt.Fprintf(out, "\tas%d %s\n", i, r.typeString(t))
		}
		out.WriteString("}\n\n")

		fmt.Fprintf(out, "func (p *%s) resolve() %s {\n", typeName, provided)
		out.WriteString("\tp.once.Do(func() {\n\t\tp.val = p.build()\n")
		for i, t := range nd.p.alsoAs {
			fmt.Fprintf(out, "\t\tv%d, ok := p.val.(%s)\n", i, r.typeString(t))
			out.WriteString("\t\tif !ok {\n")
			fmt.Fprintf(out, "\t\t\tpanic(%s.Sprintf(%q, p.val))\n", r.pkgToken("fmt"),
				"digen: "+nd.p.name+" was declared as "+typeLabel(t)+" but %T does not implement it")
			out.WriteString("\t\t}\n")
			fmt.Fprintf(out, "\t\tp.as%d = v%d\n", i, i)
		}
		out.WriteString("\t})\n\treturn p.val\n}\n\n")

		for i, t := range nd.p.alsoAs {
			fmt.Fprintf(out, "func (p *%s) resolveAs%d() %s {\n", typeName, i, r.typeString(t))
			fmt.Fprintf(out, "\tp.resolve()\n\treturn p.as%d\n}\n\n", i)
		}

		for _, m := range proxyMethods(nd.p) {
			r.renderForward(out, typeName, m.fn, m.receiver)
		}
	}
}

// proxyMethod is one forwarded method plus the expression yielding the value to
// forward to, which differs per role the provider was registered under.
type proxyMethod struct {
	fn       *types.Func
	receiver string
}

// proxyMethods is the union of the methods of the provided type and of every
// interface declared with digen.As, so the proxy satisfies all of the roles the
// provider was registered under. Deduplicated by name, since a value satisfying
// two interfaces may well share methods between them.
func proxyMethods(p *provider) []proxyMethod {
	var out []proxyMethod
	seen := map[string]bool{}

	collect := func(t types.Type, receiver string) {
		iface, ok := t.Underlying().(*types.Interface)
		if !ok {
			return
		}
		for i := range iface.NumMethods() {
			m := iface.Method(i)
			if !seen[m.Name()] {
				seen[m.Name()] = true
				out = append(out, proxyMethod{fn: m, receiver: receiver})
			}
		}
	}

	collect(p.provides, "p.resolve()")
	for i, t := range p.alsoAs {
		collect(t, fmt.Sprintf("p.resolveAs%d()", i))
	}
	return out
}

// renderForward emits one method that forwards to the real value.
func (r *renderer) renderForward(out *bytes.Buffer, typeName string, m *types.Func, receiver string) {
	sig := m.Type().(*types.Signature)

	params := sig.Params()
	args := make([]string, 0, params.Len())
	decls := make([]string, 0, params.Len())
	for i := range params.Len() {
		name := "a" + strconv.Itoa(i)
		typ := r.typeString(params.At(i).Type())
		if sig.Variadic() && i == params.Len()-1 {
			// The parameter type is a slice; render it back as variadic.
			typ = "..." + strings.TrimPrefix(typ, "[]")
			args = append(args, name+"...")
		} else {
			args = append(args, name)
		}
		decls = append(decls, name+" "+typ)
	}

	results := sig.Results()
	resultList := make([]string, 0, results.Len())
	for i := range results.Len() {
		resultList = append(resultList, r.typeString(results.At(i).Type()))
	}

	resultDecl := ""
	switch len(resultList) {
	case 0:
	case 1:
		resultDecl = " " + resultList[0]
	default:
		resultDecl = " (" + strings.Join(resultList, ", ") + ")"
	}

	fmt.Fprintf(out, "func (p *%s) %s(%s)%s {\n", typeName, m.Name(), strings.Join(decls, ", "), resultDecl)
	call := fmt.Sprintf("%s.%s(%s)", receiver, m.Name(), strings.Join(args, ", "))
	if len(resultList) == 0 {
		fmt.Fprintf(out, "\t%s\n}\n\n", call)
	} else {
		fmt.Fprintf(out, "\treturn %s\n}\n\n", call)
	}
}

func (r *renderer) renderContainer(out *bytes.Buffer) {
	fmt.Fprintf(out, "// %s builds and holds every component of the application.\n", r.g.containerType)
	out.WriteString("//\n")
	out.WriteString("// Each accessor returns the same instance every time. Accessors for\n")
	out.WriteString("// module-owned interfaces return a lazy proxy, so passing one to a\n")
	out.WriteString("// constructor does not build the component behind it.\n")
	fmt.Fprintf(out, "type %s struct {\n", r.g.containerType)

	fmt.Fprintf(out, "\t%s %s\n", r.g.diConfig.name, r.typeString(r.g.diConfig.typ))
	fmt.Fprintf(out, "\t%s *%s.Logger\n", r.loggerField(), r.pkgToken(slogPath))
	for _, in := range r.g.inputs {
		fmt.Fprintf(out, "\t%s %s\n", in.name, r.typeString(in.typ))
	}

	for _, nd := range r.g.nodes {
		name := unexportName(nd.p.name)
		switch {
		case nd.proxied:
			fmt.Fprintf(out, "\t%s *%s\n", name, r.proxyTypeName(nd.p))
		case nd.fallible:
			fmt.Fprintf(out, "\t%sOnce %s.Once\n", name, r.pkgToken("sync"))
			fmt.Fprintf(out, "\t%sVal  %s\n", name, r.typeString(nd.p.provides))
			fmt.Fprintf(out, "\t%sErr  error\n", name)
		default:
			fmt.Fprintf(out, "\t%sOnce %s.Once\n", name, r.pkgToken("sync"))
			fmt.Fprintf(out, "\t%sVal  %s\n", name, r.typeString(nd.p.provides))
		}
	}
	out.WriteString("}\n\n")

	params := make([]string, 0, len(r.g.inputs)+1)
	params = append(params, r.g.diConfig.name+" "+r.typeString(r.g.diConfig.typ))
	for _, in := range r.g.inputs {
		params = append(params, in.name+" "+r.typeString(in.typ))
	}

	fmt.Fprintf(out, "// %s wires the application. Components are built on first use,\n", r.g.containerCtor)
	out.WriteString("// and proxied ones on their first method call, so this constructs only the\n")
	out.WriteString("// components marked eager in the provider set.\n")
	fmt.Fprintf(out, "func %s(%s) (*%s, error) {\n", r.g.containerCtor, strings.Join(params, ", "), r.g.containerType)

	fmt.Fprintf(out, "\tc := &%s{%s: %s", r.g.containerType, r.g.diConfig.name, r.g.diConfig.name)
	for _, in := range r.g.inputs {
		fmt.Fprintf(out, ", %s: %s", in.name, in.name)
	}
	out.WriteString("}\n")

	// A nil logger is the common case for a caller that does not want the
	// instantiation trace, so it is tolerated rather than panicking on first use.
	fmt.Fprintf(out, "\t%s := %s.%s\n", r.loggerField(), r.g.diConfig.name, loggerField)
	fmt.Fprintf(out, "\tif %s == nil {\n", r.loggerField())
	fmt.Fprintf(out, "\t\t%s = %s.New(%s.DiscardHandler)\n", r.loggerField(), r.pkgToken(slogPath), r.pkgToken(slogPath))
	out.WriteString("\t}\n")
	fmt.Fprintf(out, "\tc.%s = %s.With(%q, %q)\n\n",
		r.loggerField(), r.loggerField(), "component", r.g.containerType)

	for _, nd := range r.g.nodes {
		if !nd.proxied {
			continue
		}
		name := unexportName(nd.p.name)
		fmt.Fprintf(out, "\tc.%s = &%s{build: func() %s {\n", name, r.proxyTypeName(nd.p), r.typeString(nd.p.provides))
		fmt.Fprintf(out, "\t\t%s\n", r.logLine(nd.p.name))
		fmt.Fprintf(out, "\t\treturn %s\n", r.callExpr(nd))
		out.WriteString("\t}}\n")
	}

	r.renderEager(out)

	out.WriteString("\treturn c, nil\n}\n\n")
}

// renderEager builds the eager components inside the constructor. A dependency
// that fails is reached through a must accessor, which panics, so the block
// recovers and returns the failure as an error instead.
func (r *renderer) renderEager(out *bytes.Buffer) {
	var eager []*node
	for _, nd := range r.g.nodes {
		if nd.p.eager {
			eager = append(eager, nd)
		}
	}
	if len(eager) == 0 {
		return
	}

	out.WriteString("\n\tif err := func() (err error) {\n")
	out.WriteString("\t\tdefer func() {\n")
	out.WriteString("\t\t\tif r := recover(); r != nil {\n")
	fmt.Fprintf(out, "\t\t\t\terr = %s.Errorf(\"eager construction: %%v\", r)\n", r.pkgToken("fmt"))
	out.WriteString("\t\t\t}\n\t\t}()\n")
	for _, nd := range eager {
		if nd.fallible {
			fmt.Fprintf(out, "\t\tif _, err := c.%s(); err != nil {\n", nd.p.name)
			fmt.Fprintf(out, "\t\t\treturn %s.Errorf(\"%s: %%w\", err)\n", r.pkgToken("fmt"), nd.p.name)
			out.WriteString("\t\t}\n")
			continue
		}
		fmt.Fprintf(out, "\t\tc.%s()\n", nd.p.name)
	}
	out.WriteString("\t\treturn nil\n")
	out.WriteString("\t}(); err != nil {\n\t\treturn nil, err\n\t}\n")
}

// logLine renders the debug line recording an instantiation. The container owns
// the component field, so the component being built is target.component.
func (r *renderer) logLine(name string) string {
	return fmt.Sprintf("c.%s.Debug(%q, %q, %q)",
		r.loggerField(), "Instantiating", "target.component", name)
}

// loggerField names the container's own logger field, avoiding any collision
// with an injected input that happens to be called the same.
func (r *renderer) loggerField() string {
	name := "diLogger"
	for {
		clash := false
		for _, in := range r.g.inputs {
			if in.name == name {
				clash = true
			}
		}
		if r.g.diConfig.name == name {
			clash = true
		}
		if !clash {
			return name
		}
		name += "_"
	}
}

func (r *renderer) renderAccessors(out *bytes.Buffer) {
	for _, nd := range r.g.nodes {
		name := nd.p.name
		field := unexportName(name)
		provided := r.typeString(nd.p.provides)

		switch {
		case nd.proxied:
			fmt.Fprintf(out, "// %s returns a lazy %s.\n", name, typeLabel(nd.p.provides))
			fmt.Fprintf(out, "func (c *%s) %s() %s {\n\treturn c.%s\n}\n\n", r.g.containerType, name, provided, field)

		case nd.fallible:
			fmt.Fprintf(out, "// %s builds %s once, caching the result including any error.\n", name, typeLabel(nd.p.provides))
			fmt.Fprintf(out, "// Dependencies are resolved in order and the first error is forwarded\n")
			fmt.Fprintf(out, "// unchanged; the recover catches a failure raised deeper, below a proxy.\n")
			fmt.Fprintf(out, "func (c *%s) %s() (%s, error) {\n", r.g.containerType, name, provided)
			fmt.Fprintf(out, "\tc.%sOnce.Do(func() {\n", field)
			fmt.Fprintf(out, "\t\t%s\n", r.logLine(name))
			out.WriteString("\t\tdefer func() {\n")
			out.WriteString("\t\t\tif rec := recover(); rec != nil {\n")
			fmt.Fprintf(out, "\t\t\t\tc.%sErr = %s.Errorf(\"%s: %%v\", rec)\n", field, r.pkgToken("fmt"), name)
			out.WriteString("\t\t\t}\n\t\t}()\n")
			r.renderFallibleBuild(out, nd, field)
			out.WriteString("\t})\n")
			fmt.Fprintf(out, "\treturn c.%sVal, c.%sErr\n}\n\n", field, field)

			if nd.needsMust {
				fmt.Fprintf(out, "func (c *%s) must%s() %s {\n", r.g.containerType, name, provided)
				fmt.Fprintf(out, "\tv, err := c.%s()\n", name)
				out.WriteString("\tif err != nil {\n")
				fmt.Fprintf(out, "\t\tpanic(%s.Errorf(\"%s: %%w\", err))\n", r.pkgToken("fmt"), name)
				out.WriteString("\t}\n\treturn v\n}\n\n")
			}

		default:
			fmt.Fprintf(out, "// %s builds %s once.\n", name, typeLabel(nd.p.provides))
			fmt.Fprintf(out, "func (c *%s) %s() %s {\n", r.g.containerType, name, provided)
			fmt.Fprintf(out, "\tc.%sOnce.Do(func() {\n", field)
			fmt.Fprintf(out, "\t\t%s\n", r.logLine(name))
			fmt.Fprintf(out, "\t\tc.%sVal = %s\n", field, r.callExpr(nd))
			out.WriteString("\t})\n")
			fmt.Fprintf(out, "\treturn c.%sVal\n}\n\n", field)
		}
	}
}

// callExpr renders the constructor call for a builder with no error return, so
// fallible dependencies go through their must accessors.
func (r *renderer) callExpr(nd *node) string {
	return r.callExprWith(nd, nil, nil)
}

// renderFallibleBuild emits the body of a fallible accessor: every fallible
// dependency is resolved in declaration order into a local, returning the first
// error unchanged, and the constructor is then called with those locals.
func (r *renderer) renderFallibleBuild(out *bytes.Buffer, nd *node, field string) {
	locals := map[*provider]string{}
	groupLocals := map[string]string{}
	used := map[string]bool{}

	fail := func(local, call string) {
		fmt.Fprintf(out, "\t\t%s, err := c.%s\n", local, call)
		out.WriteString("\t\tif err != nil {\n")
		fmt.Fprintf(out, "\t\t\tc.%sErr = err\n", field)
		out.WriteString("\t\t\treturn\n\t\t}\n")
	}

	for _, b := range nd.bindings {
		if b.input != nil {
			continue
		}
		if b.slice {
			name := r.groupNameFor(b.dep)
			if !r.groupFallible(b.dep) {
				continue
			}
			if _, done := groupLocals[name]; done {
				continue
			}
			local := uniqueLocal(used, unexportName(name))
			fail(local, name+"()")
			groupLocals[name] = local
			continue
		}
		target := b.targets[0]
		if !r.g.byProvider[target].fallible {
			continue
		}
		if _, done := locals[target]; done {
			continue
		}
		local := uniqueLocal(used, unexportName(target.name))
		fail(local, target.name+"()")
		locals[target] = local
	}

	call := r.callExprWith(nd, locals, groupLocals)
	if nd.p.fallible {
		fmt.Fprintf(out, "\t\tc.%sVal, c.%sErr = %s\n", field, field, call)
		return
	}
	fmt.Fprintf(out, "\t\tc.%sVal = %s\n", field, call)
}

// callExprWith renders the constructor call, preferring already-resolved locals
// and otherwise falling back to accessors.
func (r *renderer) callExprWith(nd *node, locals map[*provider]string, groupLocals map[string]string) string {
	args := make([]string, 0, len(nd.bindings))
	for _, b := range nd.bindings {
		switch {
		case b.input != nil:
			args = append(args, "c."+b.input.name)

		case b.slice:
			name := r.groupNameFor(b.dep)
			if local, ok := groupLocals[name]; ok {
				args = append(args, local)
				break
			}
			if r.groupFallible(b.dep) {
				args = append(args, "c.must"+name+"()")
				break
			}
			args = append(args, "c."+name+"()")

		default:
			if local, ok := locals[b.targets[0]]; ok {
				args = append(args, local)
				break
			}
			args = append(args, r.accessorCallAs(b.targets[0], b.dep))
		}
	}
	return fmt.Sprintf("%s(%s)", r.funcRef(nd.p), strings.Join(args, ", "))
}

func (r *renderer) groupFallible(elem types.Type) bool {
	for _, gr := range r.g.groups {
		if types.Identical(gr.elem, elem) {
			return gr.fallible
		}
	}
	return false
}

func uniqueLocal(used map[string]bool, base string) string {
	name := base
	for i := 2; used[name]; i++ {
		name = base + strconv.Itoa(i)
	}
	used[name] = true
	return name
}

// groupNameFor finds the slice accessor covering elem.
func (r *renderer) groupNameFor(elem types.Type) string {
	for _, gr := range r.g.groups {
		if types.Identical(gr.elem, elem) {
			return gr.name
		}
	}
	return groupName(elem, nil)
}

// renderGroups emits a slice accessor per multi-value type, so the whole set of
// implementations can be asked for directly rather than only inline at a call
// site that happens to need it.
// renderRoles emits the singular accessor for each digen.As type that exactly one
// provider fills, alongside the slice accessor every tagged type gets.
func (r *renderer) renderRoles(out *bytes.Buffer) {
	for _, ro := range r.g.roles {
		nd := r.g.byProvider[ro.target]
		typ := r.typeString(ro.typ)

		fmt.Fprintf(out, "// %s returns the %s, provided by %s.\n", ro.name, typeLabel(ro.typ), ro.target)

		if nd.fallible {
			fmt.Fprintf(out, "func (c *%s) %s() (%s, error) {\n", r.g.containerType, ro.name, typ)
			fmt.Fprintf(out, "\tv, err := c.%s()\n", ro.target.name)
			out.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			fmt.Fprintf(out, "\treturn %s, nil\n}\n\n", r.roleValue(nd, ro, "v"))
			continue
		}

		fmt.Fprintf(out, "func (c *%s) %s() %s {\n", r.g.containerType, ro.name, typ)
		switch {
		case nd.proxied:
			// The proxy implements every role it was registered under, so this
			// is checked by the compiler rather than asserted.
			fmt.Fprintf(out, "\treturn c.%s\n}\n\n", unexportName(ro.target.name))
		case r.implementsRole(nd, ro):
			fmt.Fprintf(out, "\treturn c.%s()\n}\n\n", ro.target.name)
		default:
			fmt.Fprintf(out, "\tv, ok := c.%s().(%s)\n", ro.target.name, typ)
			out.WriteString("\tif !ok {\n")
			fmt.Fprintf(out, "\t\tpanic(%s.Sprintf(%q, c.%s()))\n", r.pkgToken("fmt"),
				"digen: "+ro.target.name+" was declared as "+typeLabel(ro.typ)+" but %T does not implement it",
				ro.target.name)
			out.WriteString("\t}\n\treturn v\n}\n\n")
		}
	}
}

// roleValue renders how a already-resolved value is viewed as the role type.
func (r *renderer) roleValue(nd *node, ro role, valueVar string) string {
	if nd.proxied {
		return "c." + unexportName(ro.target.name)
	}
	if r.implementsRole(nd, ro) {
		return valueVar
	}
	return fmt.Sprintf("%s.(%s)", valueVar, r.typeString(ro.typ))
}

// satisfiesDirectly reports whether a provider's declared result can be used as
// want without going through a proxy or an assertion.
func (r *renderer) satisfiesDirectly(p *provider, want types.Type) bool {
	if types.Identical(p.provides, want) {
		return true
	}
	iface, ok := want.Underlying().(*types.Interface)
	return ok && types.Implements(p.provides, iface)
}

// implementsRole reports whether the provider's declared type already satisfies
// the role statically, in which case no conversion is needed.
func (r *renderer) implementsRole(nd *node, ro role) bool {
	iface, ok := ro.typ.Underlying().(*types.Interface)
	if !ok {
		return false
	}
	return types.Implements(nd.p.provides, iface)
}

func (r *renderer) renderGroups(out *bytes.Buffer) {
	for _, gr := range r.g.groups {
		elem := r.typeString(gr.elem)
		fmt.Fprintf(out, "// %s returns every %s, in provider set order.\n", gr.name, typeLabel(gr.elem))

		if !gr.fallible {
			fmt.Fprintf(out, "func (c *%s) %s() []%s {\n", r.g.containerType, gr.name, elem)
			fmt.Fprintf(out, "\treturn []%s{\n", elem)
			for _, t := range gr.targets {
				fmt.Fprintf(out, "\t\t%s,\n", r.accessorCallAs(t, gr.elem))
			}
			out.WriteString("\t}\n}\n\n")
			continue
		}

		// At least one member can fail, so the group resolves them in order and
		// forwards the first error rather than panicking through must.
		used := map[string]bool{}
		names := make([]string, 0, len(gr.targets))

		fmt.Fprintf(out, "func (c *%s) %s() ([]%s, error) {\n", r.g.containerType, gr.name, elem)
		for _, t := range gr.targets {
			nd := r.g.byProvider[t]
			viewed := r.satisfiesDirectly(t, gr.elem)

			// A proxied member registered under this type via digen.As is reached
			// through its proxy field, which implements the role by construction.
			// Anything else has to be resolved first, including the fallible
			// providers that have no proxy - taking those through must would
			// panic past the error return this accessor exists to provide.
			if !viewed && nd.proxied {
				names = append(names, r.accessorCallAs(t, gr.elem))
				continue
			}

			local := uniqueLocal(used, unexportName(t.name))
			if nd.fallible {
				fmt.Fprintf(out, "\t%s, err := c.%s()\n", local, t.name)
				out.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			} else {
				fmt.Fprintf(out, "\t%s := c.%s()\n", local, t.name)
			}

			if viewed {
				names = append(names, local)
				continue
			}
			names = append(names, fmt.Sprintf("%s.(%s)", local, elem))
		}
		fmt.Fprintf(out, "\treturn []%s{%s}, nil\n}\n\n", elem, strings.Join(names, ", "))

		if gr.needsMust {
			fmt.Fprintf(out, "func (c *%s) must%s() []%s {\n", r.g.containerType, gr.name, elem)
			fmt.Fprintf(out, "\tv, err := c.%s()\n", gr.name)
			out.WriteString("\tif err != nil {\n")
			fmt.Fprintf(out, "\t\tpanic(%s.Errorf(\"%s: %%w\", err))\n", r.pkgToken("fmt"), gr.name)
			out.WriteString("\t}\n\treturn v\n}\n\n")
		}
	}
}

// accessorCall renders how one provider's value is obtained from the container.
// Fallible providers go through their must accessor, matching how main resolves
// them explicitly first so their errors stay reportable.
func (r *renderer) accessorCall(p *provider) string {
	if nd, ok := r.g.byProvider[p]; ok && nd.fallible {
		return "c.must" + p.name + "()"
	}
	return "c." + p.name + "()"
}

// accessorCallAs obtains a provider's value as the type the dependency asks
// for. When digen.As registered the provider under an interface wider than its
// declared result, the accessor's return type is too narrow, so the proxy field
// is used directly — it implements every declared role, and unlike a type
// assertion it is checked by the compiler.
func (r *renderer) accessorCallAs(p *provider, want types.Type) string {
	if types.Identical(p.provides, want) || len(p.alsoAs) == 0 {
		return r.accessorCall(p)
	}
	if iface, ok := want.Underlying().(*types.Interface); ok && types.Implements(p.provides, iface) {
		return r.accessorCall(p)
	}
	if nd, ok := r.g.byProvider[p]; ok && nd.proxied {
		return "c." + unexportName(p.name)
	}
	return fmt.Sprintf("%s.(%s)", r.accessorCall(p), r.typeString(want))
}

func (r *renderer) pkgToken(path string) string {
	if _, ok := r.pkgNames[path]; !ok {
		r.pkgNames[path] = lastSegment(path)
	}
	return tokenStart + path + tokenEnd
}

// proxyTypeName names a proxy type. Proxy types are package-level, so when a
// package holds more than one provider set the container name qualifies them.
func (r *renderer) proxyTypeName(p *provider) string {
	if r.g.prefixProxies {
		return "lazy" + r.g.containerType + p.name
	}
	return "lazy" + p.name
}

func unexportName(s string) string {
	if s == "" {
		return s
	}
	// Keep leading acronyms intact: RESTController becomes restController.
	i := 0
	for i < len(s) && s[i] >= 'A' && s[i] <= 'Z' {
		i++
	}
	if i > 1 && i < len(s) {
		i--
	}
	return strings.ToLower(s[:i]) + s[i:]
}

func replaceTokens(s string, aliases map[string]string) string {
	for path, alias := range aliases {
		s = strings.ReplaceAll(s, tokenStart+path+tokenEnd, alias)
	}
	// Any remaining token is a reference to the package being generated into.
	for {
		start := strings.Index(s, tokenStart)
		if start < 0 {
			break
		}
		end := strings.Index(s[start+len(tokenStart):], tokenEnd)
		if end < 0 {
			break
		}
		s = s[:start] + s[start+len(tokenStart)+end+len(tokenEnd):]
		// Drop the selector dot left behind by a same-package qualifier.
		if start < len(s) && s[start] == '.' {
			s = s[:start] + s[start+1:]
		}
	}
	return s
}

func lastSegment(path string) string {
	if i := strings.LastIndex(path, "/"); i >= 0 {
		return path[i+1:]
	}
	return path
}

func parentSegment(path string) string {
	segs := strings.Split(path, "/")
	if len(segs) < 2 {
		return ""
	}
	return segs[len(segs)-2]
}

func sanitizeIdent(s string) string {
	var b strings.Builder
	for _, r := range s {
		if r == '-' || r == '.' {
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}

func numberLines(s string) string {
	lines := strings.Split(s, "\n")
	var b strings.Builder
	for i, l := range lines {
		fmt.Fprintf(&b, "%4d| %s\n", i+1, l)
	}
	return b.String()
}
