// Code generated by digen. DO NOT EDIT.

package main

import (
	fmt "fmt"
	digen "github.com/Nethron-Inc/digen"
	config "github.com/Nethron-Inc/digen/examples/basic/config"
	greeting "github.com/Nethron-Inc/digen/examples/basic/greeting"
	notify "github.com/Nethron-Inc/digen/examples/basic/notify"
	store "github.com/Nethron-Inc/digen/examples/basic/store"
	slog "log/slog"
	sync "sync"
)

// lazyGreeter defers construction of greeting.Greeter until first use.
type lazyGreeter struct {
	once  sync.Once
	build func() greeting.Greeter
	val   greeting.Greeter
}

func (p *lazyGreeter) resolve() greeting.Greeter {
	p.once.Do(func() {
		p.val = p.build()
	})
	return p.val
}

func (p *lazyGreeter) Greet(a0 string) string {
	return p.resolve().Greet(a0)
}

// lazyConsoleNotifier defers construction of notify.Notifier until first use.
type lazyConsoleNotifier struct {
	once  sync.Once
	build func() notify.Notifier
	val   notify.Notifier
	as0   notify.Starter
}

func (p *lazyConsoleNotifier) resolve() notify.Notifier {
	p.once.Do(func() {
		p.val = p.build()
		v0, ok := p.val.(notify.Starter)
		if !ok {
			panic(fmt.Sprintf("digen: ConsoleNotifier was declared as notify.Starter but %T does not implement it", p.val))
		}
		p.as0 = v0
	})
	return p.val
}

func (p *lazyConsoleNotifier) resolveAs0() notify.Starter {
	p.resolve()
	return p.as0
}

func (p *lazyConsoleNotifier) Notify(a0 string) string {
	return p.resolve().Notify(a0)
}

func (p *lazyConsoleNotifier) Start() {
	p.resolveAs0().Start()
}

// AppContainer builds and holds every component of the application.
//
// Each accessor returns the same instance every time. Accessors for
// module-owned interfaces return a lazy proxy, so passing one to a
// constructor does not build the component behind it.
type AppContainer struct {
	diCfg             digen.ContainerConfig
	diLogger          *slog.Logger
	cfg               config.Config
	greeter           *lazyGreeter
	storeOnce         sync.Once
	storeVal          store.Store
	storeErr          error
	consoleNotifier   *lazyConsoleNotifier
	auditNotifierOnce sync.Once
	auditNotifierVal  notify.Notifier
	auditNotifierErr  error
	registryOnce      sync.Once
	registryVal       *notify.Registry
	registryErr       error
}

// NewAppContainer wires the application. Components are built on first use,
// and proxied ones on their first method call, so this constructs only the
// components marked eager in the provider set.
func NewAppContainer(diCfg digen.ContainerConfig, cfg config.Config) (*AppContainer, error) {
	c := &AppContainer{diCfg: diCfg, cfg: cfg}
	diLogger := diCfg.Logger
	if diLogger == nil {
		diLogger = slog.New(slog.DiscardHandler)
	}
	c.diLogger = diLogger.With("component", "AppContainer")

	c.greeter = &lazyGreeter{build: func() greeting.Greeter {
		c.diLogger.Debug("Instantiating", "target.component", "Greeter")
		return greeting.NewGreeter(c.cfg)
	}}
	c.consoleNotifier = &lazyConsoleNotifier{build: func() notify.Notifier {
		c.diLogger.Debug("Instantiating", "target.component", "ConsoleNotifier")
		return notify.NewConsoleNotifier(c.Greeter())
	}}

	if err := func() (err error) {
		defer func() {
			if r := recover(); r != nil {
				err = fmt.Errorf("eager construction: %v", r)
			}
		}()
		if _, err := c.Registry(); err != nil {
			return fmt.Errorf("Registry: %w", err)
		}
		return nil
	}(); err != nil {
		return nil, err
	}
	return c, nil
}

// Greeter returns a lazy greeting.Greeter.
func (c *AppContainer) Greeter() greeting.Greeter {
	return c.greeter
}

// Store builds store.Store once, caching the result including any error.
// Dependencies are resolved in order and the first error is forwarded
// unchanged; the recover catches a failure raised deeper, below a proxy.
func (c *AppContainer) Store() (store.Store, error) {
	c.storeOnce.Do(func() {
		c.diLogger.Debug("Instantiating", "target.component", "Store")
		defer func() {
			if rec := recover(); rec != nil {
				c.storeErr = fmt.Errorf("Store: %v", rec)
			}
		}()
		c.storeVal, c.storeErr = store.NewStore(c.cfg)
	})
	return c.storeVal, c.storeErr
}

// ConsoleNotifier returns a lazy notify.Notifier.
func (c *AppContainer) ConsoleNotifier() notify.Notifier {
	return c.consoleNotifier
}

// AuditNotifier builds notify.Notifier once, caching the result including any error.
// Dependencies are resolved in order and the first error is forwarded
// unchanged; the recover catches a failure raised deeper, below a proxy.
func (c *AppContainer) AuditNotifier() (notify.Notifier, error) {
	c.auditNotifierOnce.Do(func() {
		c.diLogger.Debug("Instantiating", "target.component", "AuditNotifier")
		defer func() {
			if rec := recover(); rec != nil {
				c.auditNotifierErr = fmt.Errorf("AuditNotifier: %v", rec)
			}
		}()
		store, err := c.Store()
		if err != nil {
			c.auditNotifierErr = err
			return
		}
		c.auditNotifierVal, c.auditNotifierErr = notify.NewAuditNotifier(store)
	})
	return c.auditNotifierVal, c.auditNotifierErr
}

// Registry builds *notify.Registry once, caching the result including any error.
// Dependencies are resolved in order and the first error is forwarded
// unchanged; the recover catches a failure raised deeper, below a proxy.
func (c *AppContainer) Registry() (*notify.Registry, error) {
	c.registryOnce.Do(func() {
		c.diLogger.Debug("Instantiating", "target.component", "Registry")
		defer func() {
			if rec := recover(); rec != nil {
				c.registryErr = fmt.Errorf("Registry: %v", rec)
			}
		}()
		notifiers, err := c.Notifiers()
		if err != nil {
			c.registryErr = err
			return
		}
		c.registryVal = notify.NewRegistry(notifiers)
	})
	return c.registryVal, c.registryErr
}

// Starter returns the notify.Starter, provided by notify.NewConsoleNotifier.
func (c *AppContainer) Starter() notify.Starter {
	return c.consoleNotifier
}

// Notifiers returns every notify.Notifier, in provider set order.
func (c *AppContainer) Notifiers() ([]notify.Notifier, error) {
	consoleNotifier := c.ConsoleNotifier()
	auditNotifier, err := c.AuditNotifier()
	if err != nil {
		return nil, err
	}
	return []notify.Notifier{consoleNotifier, auditNotifier}, nil
}

// Starters returns every notify.Starter, in provider set order.
func (c *AppContainer) Starters() []notify.Starter {
	return []notify.Starter{
		c.consoleNotifier,
	}
}
